//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafocha.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderNote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderNote()
        {
            this.OrderNoteDetails = new HashSet<OrderNoteDetail>();
        }
    
        public string ordernote_id { get; set; }
        public int pay_method { get; set; }
        public decimal sale_value { get; set; }
        public decimal total_price_non_disc { get; set; }
        public decimal Vat { get; set; }
        public int discount { get; set; }
        public string cus_id { get; set; }
        public string emp_id { get; set; }
        public System.DateTime order_time { get; set; }
        public decimal total_price { get; set; }
        public decimal customer_pay { get; set; }
        public decimal pay_back { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderNoteDetail> OrderNoteDetails { get; set; }
    }
}
