//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafocha.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderNoteDetail
    {
        public string ordernote_id { get; set; }
        public string product_id { get; set; }
        public int discount { get; set; }
        public int quan { get; set; }
    
        public virtual OrderNote OrderNote { get; set; }
        public virtual Product Product { get; set; }
    }
}
