//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafocha.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryNote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalaryNote()
        {
            this.WorkingHistories = new HashSet<WorkingHistory>();
        }
    
        public string sn_id { get; set; }
        public string emp_id { get; set; }
        public Nullable<System.DateTime> date_pay { get; set; }
        public decimal salary_value { get; set; }
        public double work_hour { get; set; }
        public int for_month { get; set; }
        public int for_year { get; set; }
        public byte is_paid { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkingHistory> WorkingHistories { get; set; }
    }
}
