//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafocha.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockOutDetail
    {
        public string stockout_id { get; set; }
        public string sto_id { get; set; }
        public int quan { get; set; }
        public decimal item_price { get; set; }
        public string note { get; set; }
    
        public virtual Stock Stock { get; set; }
        public virtual StockOut StockOut { get; set; }
    }
}
