//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafocha.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkingHistory
    {
        public string wh_id { get; set; }
        public string result_salary { get; set; }
        public string emp_id { get; set; }
        public System.DateTime startTime { get; set; }
        public System.DateTime endTime { get; set; }
        public int is_paid { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual SalaryNote SalaryNote { get; set; }
    }
}
